'use strict';
let results=null;
const quiz=document.getElementById('quiz'),result=document.getElementById('result'),error=document.getElementById('error');
const dataReady=fetch('results.json').then(r=>{if(!r.ok)throw new Error('Unable to load');return r.json()}).then(data=>{results=data;return data}).catch(()=>null);
async function selectRest(choice){if(!['A','B','C','D'].includes(choice))throw new Error('Invalid choice');await dataReady;if(!results){error.hidden=false;return {error:'results_unavailable'}};const data=results[choice];document.getElementById('result-choice').textContent=choice+' · '+data.name;document.getElementById('result-title').textContent=data.title;document.getElementById('intro').textContent=data.intro;const body=document.getElementById('paragraphs');body.replaceChildren(...data.paragraphs.map(text=>{const p=document.createElement('p');p.textContent=text;return p}));document.getElementById('signals').replaceChildren(...data.signals.map(text=>{const li=document.createElement('li');li.textContent=text;return li}));document.getElementById('reminder').textContent=data.reminder;document.getElementById('practice').textContent=data.practice;document.getElementById('practice-detail').textContent=data.practiceDetail;document.getElementById('closing').textContent=data.closing;quiz.hidden=true;result.hidden=false;document.getElementById('result-title').focus({preventScroll:true});window.scrollTo({top:0,behavior:'auto'});return {choice,title:data.title,practice:data.practice};}
function resetRest(){result.hidden=true;quiz.hidden=false;error.hidden=true;document.querySelector('[data-choice="A"]').focus({preventScroll:true});window.scrollTo({top:0,behavior:'auto'});return {view:'quiz'};}
document.querySelectorAll('[data-choice]').forEach(button=>button.addEventListener('click',()=>selectRest(button.dataset.choice)));
document.getElementById('reset').addEventListener('click',resetRest);
if(document.modelContext?.registerTool){const controller=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'select_rest_picture',title:'選擇休息畫面',description:'選擇 A 睡覺、B 散步、C 吃飯聊天或 D 畫畫，顯示對應的休息解析。',inputSchema:{type:'object',properties:{choice:{type:'string',enum:['A','B','C','D']}},required:['choice'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>selectRest(input.choice)},{signal:controller.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>controller.abort(),{once:true});}
