const results={
A:{name:'自由',label:'A｜獨自旅行',title:'妳嚮往的幸福，是能自己決定',lead:'想去哪裡、想怎麼過，終於可以先問問自己',paragraphs:['如果這個畫面吸引妳，也許妳最近很想有一段不必配合別人的時間。平常要顧工作、顧關係，連休息都得先看看別人方不方便，久了會想念那個可以隨興一點的自己。','看見別人去旅行、換一種生活，妳羨慕的可能不只是風景，還有他們說走就走的自在。妳也想試試看，照著自己的心意安排一天會是什麼感覺。','自由可以從很小的選擇開始。這個週末想去哪裡逛、今晚想吃什麼、哪件事今天先不答應，都可以留一點空間給自己。'],practice:'留一小段只屬於妳的時間，去一個一直想去的地方。不必等到有人能陪妳，也不用把行程排得很滿。',closing:'妳也可以讓自己的喜歡，成為出發的理由'},
B:{name:'被愛',label:'B｜有人陪伴',title:'妳嚮往的幸福，是有人把妳放在心上',lead:'不用一直很堅強，也有人願意靠近妳',paragraphs:['如果妳選了依偎的畫面，也許妳最近特別在意有人能聽妳說話、記得妳的小事。忙了一整天，最想要的可能只是一句「今天還好嗎」，和一個可以放心靠過去的肩膀。','看見別人被照顧、被惦記，妳心裡也許會浮出「如果我也有就好了」。有這個念頭很正常，想被愛、想被陪伴，本來就是可以說出口的需要。','但別把別人的甜蜜，變成對自己的否定。現在有沒有伴侶，不能替妳的價值打分數。妳值得被好好對待，也可以練習靠近那些讓妳感到安心的人。'],practice:'找一位讓妳自在的人，說一句真實的近況。如果想要陪伴，可以直接說「這週有空一起吃飯嗎」。',closing:'可以羨慕別人被愛，也別因此覺得自己不夠好'},
C:{name:'成就',label:'C｜完成目標',title:'妳嚮往的幸福，是看見努力有了成果',lead:'想親眼看見，自己慢慢做成一件事',paragraphs:['如果完成作品的畫面讓妳心動，也許妳最近很想得到一份具體的回應。花了時間、用了心，會希望看見成果，也希望有人懂得這件事對妳有多重要。','當朋友加薪、買房，或做成一直想做的事，妳可能一邊替他開心，一邊問自己「那我呢」。那份失落，也許是在提醒妳：妳也有一件很想完成的事。','可以把注意力慢慢放回自己的目標。先挑一件妳在意的事，把它縮成這週做得到的一小步。成果不用跟別人的一樣大，能看見自己往前一點，就值得留意。'],practice:'寫下一件妳想完成的事，再選出一個今天就能開始的小步驟。做完後，給自己一句具體的肯定。',closing:'妳的努力，不需要靠贏過誰才有意義'},
D:{name:'安定',label:'D｜自在休息',title:'妳嚮往的幸福，是不用趕的安心',lead:'今天沒有特別的安排，也能舒服地過',paragraphs:['如果妳選了安靜閱讀的畫面，也許妳最近更想要的是生活有一點餘裕。事情一件接一件，訊息總是回不完，連放空都會想到還有哪些事沒做。','看見別人的生活很精彩，妳可能也會擔心自己太平淡。但熱鬧不一定是妳現在需要的。能睡得好、好好吃飯、在熟悉的地方安心待著，也是一種妳可以選擇的幸福。','妳可以給自己一個不用交代成果的晚上。少安排一件事，把注意力放在身體和心情。當生活的步調稍微鬆一點，妳也比較有空間感受什麼真的讓自己舒服。'],practice:'今晚留半小時不排任何待辦，泡杯喜歡的飲料、看幾頁書，或單純坐著休息。',closing:'平靜的日子，也值得被妳好好喜歡'}
};
function selectChoice(choice){if(!Object.hasOwn(results,choice))throw new Error('請選擇 A、B、C 或 D');const r=results[choice];document.querySelector('#result-label').textContent=r.label;document.querySelector('#result-title').textContent=r.title;document.querySelector('#result-lead').textContent=r.lead;document.querySelector('#result-body').replaceChildren(...r.paragraphs.map(t=>{const p=document.createElement('p');p.textContent=t;return p}));document.querySelector('#practice').textContent=r.practice;document.querySelector('#closing').textContent=r.closing;document.querySelector('#selection').hidden=true;document.querySelector('#result').hidden=false;document.querySelector('header').hidden=true;window.scrollTo({top:0,behavior:'instant'});document.querySelector('#result-title').focus({preventScroll:true});return {choice,happiness:r.name,title:r.title}}
function resetQuiz(){document.querySelector('#selection').hidden=false;document.querySelector('#result').hidden=true;document.querySelector('header').hidden=false;window.scrollTo({top:0,behavior:'instant'});document.querySelector('[data-choice="A"]').focus({preventScroll:true})}
document.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>selectChoice(b.dataset.choice)));document.querySelector('#reset').addEventListener('click',resetQuiz);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'select_happiness_picture',description:'選擇 A、B、C 或 D，顯示對應的幸福需求解析',inputSchema:{type:'object',properties:{choice:{type:'string',enum:['A','B','C','D']}},required:['choice'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input!=='object'||Object.keys(input).length!==1)throw new Error('請提供一個選項');return selectChoice(input.choice)}})).catch(()=>{})}catch{}}
